# Generated by Django 4.2 on 2023-04-11 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='number_rating',
            new_name='number_review',
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(verbose_name=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
